spring:
  datasource:
    url: jdbc:h2:./target/local_db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  h2:
    console:
      enabled: true
server:
  port: 8888
